# Generated by Django 3.2 on 2021-05-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('matiere', 'etudiant')},
        ),
    ]
